### PR TITLE
allowed compressed bodies

### PR DESCRIPTION
**Pull request by evanmcc**
This PR is meant to allow hermes (and any other service, really) to send compressed bodies to save bandwidth and/or packet count.  There are no tests that exercise the HTTP path that I could see, so I could not test this.  However the code was modified from working code in l2met, so there is some expectation that it will work.  We should test extensively in staging in any case.

cc @voidlock

### CODE REVIEW

**Comment by voidlock** [comment]
This gets a 👍  from me, but @heroku/foundation should review it as well

**Comment by curzonj** [comment]
I've created an issue to track testing and deploying that. Foundation doesn't have any experience with golang nor log-iss, so validating and testing the change will take some time.

**Comment by evanmcc** [comment]
Let us know how we can help.  We can write a detailed test plan if it would
help.

**Comment by CobyR** [comment]
@voidlock @evanmcc Does this PR still need to be merged?  @curzonj mentioned that it may not be valid at this point?

**Comment by curzonj** [comment]
are there any deployment docs on log-iss? I don't know how to deploy it nor how to test it in staging.

**Comment by curzonj** [comment]
+1

**Comment by voidlock** [comment]
I do not believe there are any playbooks around deployment. `log-iss` is packaged up as a `.deb` file and pushed to packagecloud. From there I would normally just use deploymaster to `apt-get update && apt-get install` the new version on the splunk instances.

Is there a staging splunk cluster?

**Pull request merged**
