### PR TITLE
Miscellaneous tweaks

### PR DESCRIPTION
**Pull request by cyx**
- Makes nilVal a global var to avoid allocating everytime
- Remove unused readCopy var

### CODE REVIEW

**Comment by cyx** [comment]
@freeformz ^ would appreciate :eyes:

**Comment by freeformz** [comment]
Sorry, was out on vacation. LGTM

**Comment by cyx** [comment]
Hi @freeformz,

So the extra TeeReader bit wasn't necessary? Just wanted to make sure.

**Comment by freeformz** [comment]
It is... see https://github.com/heroku/log-iss/pull/12, where I removed it (and other cleanups).

**Comment by cyx** [comment]
Haha didn't realize. Yes thanks!

**Comment by freeformz** [comment]
@cyx any chance of getting #12  merged?

**Comment by cyx** [comment]
I'll cherry pick the remaining and merge that tomorrow. Thanks!

**Comment by freeformz** [comment]
Cool!

**Pull request merged**
